<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.2.0" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
		<PackageReference Include="MediatR" Version="14.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.14" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Readora.Application\Readora.Application.csproj" />
    <ProjectReference Include="..\Readora.Infrastructure\Readora.Infrastructure.csproj" />
  </ItemGroup>

</Project>
